import test from 'node:test'
import assert from 'node:assert/strict'
import { createFinance, normalizeFinance, applyFinance, balances, reservedByAccount, overview, parseMoney, monthlySaving, dueDate, billPaid, localDate } from '../src/utils/finance.js'
const month = localDate().slice(0, 7)
const date = localDate()
const account = (f, id, opening = 100000, currency = 'CRC') => applyFinance(f, { type: 'account.save', payload: { id, name: id, kind: 'bank', currency, opening } })
const transaction = (f, p) => applyFinance(f, { type: 'transaction.add', payload: { id: 'tx', date, type: 'expense', accountId: 'a', amount: 1000, ...p } })
const goal = f => applyFinance(f, { type: 'saving.save', payload: { id: 'g', name: 'Compra', currency: 'CRC', target: 50000, deadline: '' } })
const bill = f => applyFinance(f, { type: 'bill.save', payload: { id: 'b', name: 'Internet', amount: 10000, currency: 'CRC', day: 31, startMonth: month } })
const allocate = (f, amount, direction = 'reserve') => applyFinance(f, { type: 'saving.allocate', payload: { id: 'g', accountId: 'a', amount, direction } })

test('money parsing preserves cents and rejects ambiguous/invalid input', () => {
  assert.equal(parseMoney('0.29'), 29)
  assert.equal(parseMoney('100,50'), 10050)
  assert.equal(parseMoney('0', true), 0)
  for (const value of ['', '-10', 'NaN', 'Infinity', '1e4', '1,000.00', '0.001', '0']) assert.throws(() => parseMoney(value))
})
test('legacy app data receives empty finance state without sample balances', () => {
  assert.deepEqual(normalizeFinance(undefined), createFinance())
  const state = normalizeFinance({ version: 1, accounts: null, currency: 'EUR' })
  assert.deepEqual(state.accounts, [])
  assert.equal(state.currency, 'CRC')
})
test('different currencies are never added together; opening balances are not income', () => {
  const f = account(account(account(createFinance(), 'a', 20000), 'b', 30000), 'usd', 7000, 'USD')
  assert.equal(overview(f, 'CRC', month).total, 50000)
  assert.equal(overview(f, 'USD', month).total, 7000)
  assert.equal(overview(f, 'CRC', month).income, 0)
})
test('transfers conserve the total and are excluded from income and expense', () => {
  const before = account(account(createFinance(), 'a'), 'b', 0)
  const after = transaction(before, { type: 'transfer', toAccountId: 'b', amount: 30000 })
  assert.deepEqual(balances(after), { a: 70000, b: 30000 })
  assert.equal(overview(after, 'CRC', month).total, 100000)
  assert.equal(overview(after, 'CRC', month).income, 0)
  assert.equal(overview(after, 'CRC', month).expense, 0)
  assert.deepEqual(balances(before), { a: 100000, b: 0 }, 'input is immutable')
})
test('transfers reject same account, missing destination, currency mismatch, and overdraft', () => {
  const f = account(account(account(createFinance(), 'a'), 'b', 0), 'usd', 0, 'USD')
  for (const p of [{ toAccountId: 'a' }, { toAccountId: 'missing' }, { toAccountId: 'usd' }, { toAccountId: 'b', amount: 200000 }]) assert.throws(() => transaction(f, { type: 'transfer', ...p }))
})
test('a recurring payment affects the balance once and removing it reopens the bill', () => {
  const before = bill(account(createFinance(), 'a'))
  const paid = transaction(before, { amount: 10000, billId: 'b', billMonth: month })
  assert.equal(balances(paid).a, 90000)
  assert.equal(overview(paid, 'CRC', month).pending, 0)
  assert.equal(overview(paid, 'CRC', month).expense, 10000)
  assert.equal(overview(paid, 'CRC', month).available, overview(before, 'CRC', month).available)
  assert.throws(() => transaction(paid, { id: 'again', amount: 10000, billId: 'b', billMonth: month }))
  const undone = applyFinance(paid, { type: 'transaction.delete', payload: { id: 'tx' } })
  assert.equal(billPaid(undone, 'b', month), false)
  assert.equal(balances(undone).a, 100000)
})
test('recurring bills restart next month and clamp to the last calendar day', () => {
  assert.equal(dueDate({ day: 31 }, '2026-02'), '2026-02-28')
  assert.equal(dueDate({ day: 31 }, '2028-02'), '2028-02-29')
  let f = bill(account(createFinance(), 'a'))
  f = transaction(f, { billId: 'b', billMonth: month, amount: 10000 })
  const next = new Date(); next.setDate(1); next.setMonth(next.getMonth() + 1)
  assert.equal(overview(f, 'CRC', localDate(next).slice(0, 7)).pending, 10000)
  assert.equal(overview(f, 'CRC', '2000-01').monthly, 0)
})
test('saving allocations reserve existing funds without duplicating or spending money', () => {
  const f = allocate(goal(account(createFinance(), 'a')), 30000)
  assert.equal(balances(f).a, 100000)
  assert.equal(reservedByAccount(f).a, 30000)
  assert.equal(overview(f, 'CRC', month).total, 100000)
  assert.equal(overview(f, 'CRC', month).expense, 0)
  assert.equal(overview(f, 'CRC', month).available, 70000)
  assert.equal(reservedByAccount(allocate(f, 10000, 'release')).a, 20000)
  assert.throws(() => allocate(f, 40000, 'release'))
  assert.throws(() => allocate(f, 30000))
  assert.throws(() => transaction(f, { amount: 80000 }))
})
test('reservations cannot exceed account funds or mix currencies', () => {
  const f = goal(account(account(createFinance(), 'a', 500), 'usd', 100000, 'USD'))
  assert.throws(() => allocate(f, 1000))
  assert.throws(() => applyFinance(f, { type: 'saving.allocate', payload: { id: 'g', accountId: 'usd', amount: 500, direction: 'reserve' } }))
})
test('deleting a saving releases reservations; deleting used accounts is blocked', () => {
  const f = allocate(goal(account(createFinance(), 'a')), 30000)
  assert.throws(() => applyFinance(f, { type: 'account.delete', payload: { id: 'a' } }))
  const released = applyFinance(f, { type: 'saving.delete', payload: { id: 'g' } })
  assert.equal(overview(released, 'CRC', month).available, 100000)
  assert.throws(() => applyFinance(transaction(released, {}), { type: 'account.delete', payload: { id: 'a' } }))
})
test('monthly saving includes current and deadline months and handles expired goals', () => {
  const g = { target: 10001, allocations: {}, deadline: '2026-12-20' }
  assert.equal(monthlySaving(g, '2026-10'), 3334)
  assert.equal(monthlySaving(g, '2027-01'), 10001)
  assert.equal(monthlySaving({ ...g, allocations: { a: 10001 } }, '2026-10'), 0)
  assert.equal(monthlySaving({ ...g, deadline: '' }, '2026-10'), 0)
})
test('deleting an income that has been spent cannot make an account negative', () => {
  let f = transaction(account(createFinance(), 'a', 0), { id: 'income', type: 'income', amount: 1000 })
  f = transaction(f, { id: 'spent', amount: 1000 })
  assert.throws(() => applyFinance(f, { type: 'transaction.delete', payload: { id: 'income' } }))
})
test('invalid transactions do not enter the ledger', () => {
  const f = account(createFinance(), 'a')
  for (const p of [{ amount: NaN }, { amount: -1 }, { amount: 0 }, { amount: 0.5 }, { date: '2026-02-30' }, { date: '9999-01-01' }, { accountId: 'unknown' }]) assert.throws(() => transaction(f, p))
})
test('state round-trip retains accounts, movements, bills and reservations', () => {
  let f = bill(allocate(goal(account(createFinance(), 'a')), 20000))
  f = transaction(f, { amount: 10000 })
  const restored = normalizeFinance(JSON.parse(JSON.stringify(f)))
  assert.deepEqual(overview(restored, 'CRC', month), overview(f, 'CRC', month))
  assert.deepEqual(restored, f)
})
